### ISSUE TITLE
코드가 너무 러프해요

### ISSUE THREAD

**Issue by Nuung** [2hanbyeol1/searchright-blog#1]
coderabbit 같은걸 직접 붙여보는 것은 어떨까요?
GPT 로 만드는 것보다는 나으면 좋겠어요!!

**Comment by 2hanbyeol1** [comment]
![image](https://github.com/user-attachments/assets/b6846efa-18a9-4826-bef0-167496924d87)
coderabbit 연결했는데 `full review`가 안돼요... 끄아아악
